[package]
name = "fadeluc-123/leaderboard"
description = "A package conversion of an existing leaderboard module, view original at https://github.com/arxkdev/Leaderboard"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
authors = [
    "Michael Sumner <mike@whiteoak.studio>"
]

include = [
    "src",
    "src/init.lua",
    "default.project.json",
    "wally.toml",
    "src/Modules",
]

[dependencies]
Promise = "evaera/promise@^4.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"