[package]
name = "fadeluc-123/leaderboard"
description = "A package conversion of an existing leaderboard module, view original at https://github.com/arxkdev/Leaderboard"
version = "1.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
authors = [
    "Michael Sumner <mike@whiteoak.studio>"
]

include = [
    "src",
    "src/init.luau",
    "default.project.json",
    "wally.toml",
    "src/Modules",

    "src/Board",
    "src/Board/init.luau",
    "src/Board/MemoryShard.luau",

    "src/Util",
    "src/init.luau",
    "src/Util/Compression.luau",
    "src/Util/Sha1.luau",

    "src/Logger.luau",
    "src/Promise.luau",
    "src/Signal.luau",
    "src/UserIdCache.luau",
]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"